### ISSUE TITLE
Problem with latex-git-log

### ISSUE THREAD

**Issue by Tjalf2** [ypid/typesetting#3] opened 2019-04-20 17:33 UTC
Der Schneider,
i have a problem with your script. Those two errors occurred with diffrent operations. Have i done something wrong or is there i way to fix this. I would realy like to use your script.
Thanks for your help.
`C:\Users>perl latex-git-log --author --width=6 --lang=en > example-output.tex
fatal: ambiguous argument '&': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
"git" unexpectedly returned exit value 128 at latex-git-log line 139.`

`C:\Users>perl latex-git-log --width=6 --lang=en > example-output.tex
fatal: ambiguous argument '%ad': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
"git" unexpectedly returned exit value 128 at latex-git-log line 139.`

**Comment by ypid** [comment] 2019-04-22 08:06
Have you tried the latest development version (https://github.com/ypid/typesetting/tree/%232/scripts/latex-git-log)? There has been some recent changes in #2 which are not yet merged. Also, you are using Windows and if the issue is Windows specific, I am not very open to invest time into supporting that OS but I am open to PR.

**Closed as completed** 2024-05-29 19:52 UTC
